urls.py
from django.conf.urls import url
from . import views

app_name = 'post'
urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^writepost/(?P<pk>[0-9])$', views.DetailView.as_view(), name='post'),
	]

models.py
import datetime

from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible

@python_2_unicode_compatible
class Post(models.Model):

    def __str__(self):
	    return self.post_title
    def __str__(self):
    	return self.post_content
    def __str__(self):
    	return self.username
    def __str__(self):
    	return self.password
    def blog_id(self):
    	return self.blog_id
    def post_author(self):
    	return self.post_author

    def datetime(self):
    	return now
    now=timezone.now()
    def __str__(self):
    	return self.post_format


    post_status = "publish"
    comment_status = "open"
    post_parent = 0
    post_format = "standard"
    post_excerpt = ""
    post_type = "post"
    ping_status = "open"
    sticky = 0


    post_title = models.CharField(max_length=150)
    pub_date = models.DateTimeField('date published')
    body = models.CharField(max_length=10000)

class Comment(models.Model):
    def __str__(self):
        return self.comment_text
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=200)

views.py
from django.http import HttpResponse, HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.utils import timezone
#from django.template import loader
from django.shortcuts import get_object_or_404, render
from django.views import generic

from .models import Post, Comment


class IndexView(generic.ListView):
	template_name = 'post/index.html'
	context_object_name = 'latest_articles'

	def get_queryset(self):
		return Post.objects.filter(
			pub_date__lte = timezone.now()
			).order_by('-pub_date')[:10]
	def index(request):
		latest_articles = Post.objects.order_by('-pub_date')[:10]
		context = {
			'latest_articles':latest_articles,
		}


class DetailView(generic.DetailView):
	model = Post
	template_name = 'post/writepost.html'
	

class viewOfPost(generic.DetailView):
	model = Post
	template_name = 'post/viewOfPost.html'



# Create your views here.

templates/post/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'post/style.css' %}" />

{% if post_set %}

<h1> Published posts</h1>


    <ul>
    {% for post in post_set %}
        <li>{{ post_title}}</li>
    {% endfor %}
    </ul>
{% else %}
    <p>No posts are available.</p>
{% endif %}

<br/>
<button><a href="{% url 'post:post' %}">Create A New Post!</a></button>

templates/post/viewOfPost.html
<h1> Title: {{ post.post_title}}</h1>

<br/><br/>

<h2>Content:</h2><br/>
<p>{{post.post_content}}</p>



<h2> Thanks for posting!</h2>

templates/post/writepost.html
<h1> Write your post here</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
<form action="{% url 'post:post' post.id %}" method="post">
{% csrf_token %}
	<h2>Title: </h2><br/>
    <input type="text" name="post_title" id="post_title" value="{{post_title}}"/><br/><br/>
    <h2>Content: </h2><br/>
    <input type="text" name="content_text" id="post_content" value="{{post_content}}"/><br/><br/>

{% endfor %}
<input type="submit" value="Publish" />
</form>